name: Deploy to Firebase Hosting on merge
on:
  workflow_dispatch: 
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd client && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: 'client'
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONIONTEMPLATE }}
          channelId: live
          projectId: oniontemplate
